# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set environment variables
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "JWT_EXPIRE=${{ secrets.JWT_EXPIRE }}" >> .env
        echo "COOKIE_EXPIRE=${{ secrets.COOKIE_EXPIRE }}" >> .env
        echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
        echo "REDIRECT_PORT1=${{ secrets.REDIRECT_PORT1 }}" >> .env
        echo "REDIRECT_PORT2=${{ secrets.REDIRECT_PORT2 }}" >> .env
        echo "REDIRECT_PORT3=${{ secrets.REDIRECT_PORT3 }}" >> .env
        echo "TEMPLATE_PORT=${{ secrets.TEMPLATE_PORT }}" >> .env
        echo "TEMPLATE_PORT2=${{ secrets.TEMPLATE_PORT2 }}" >> .env
        echo "TEMPLATE_PORT3=${{ secrets.TEMPLATE_PORT3 }}" >> .env
        echo "TEMPLATE_PORT4=${{ secrets.TEMPLATE_PORT4 }}" >> .env
        echo "BUTTON_PORT=${{ secrets.BUTTON_PORT }}" >> .env
        echo "TEMPLATE1=${{ secrets.TEMPLATE1 }}" >> .env
        echo "REDIRECT1=${{ secrets.REDIRECT1 }}" >> .env
        echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
        echo "BUTTON1=${{ secrets.BUTTON1 }}" >> .env
        echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> .env
        echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
        echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
        echo "REDIRECT2=${{ secrets.REDIRECT2 }}" >> .env
        echo "REDIRECT3=${{ secrets.REDIRECT3 }}" >> .env
        echo "TEMPLATE2=${{ secrets.TEMPLATE2 }}" >> .env
        echo "TEMPLATE3=${{ secrets.TEMPLATE3 }}" >> .env
      

        
        
    - run: npm ci
    - run: npm run build --if-present
    - run: pm2 restart ads-network-back-end -i max
